#!/usr/bin/env bash

HOST=$1
SERVICE=$2
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PATH_TO_DEPLOY="${SCRIPT_DIR}/../../deploy"
if [ -z "${PATH_TO_DEPLOY}" ]
then
    printf "Please set PATH_TO_DEPLOY\n"
    exit 1
fi
HOST_FILE="${PATH_TO_DEPLOY}/hosts/${HOST}_hosts.txt"

sed -n -e "/\[${SERVICE}/,/^$/ p" "${HOST_FILE}"
